apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels:
    host: https://www.ub-speeda.com/v1/systems/ping
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
